on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - run: docker build --build-arg PLATFORM=arm64 .
