on:
  release:
    types:
      - prereleased

jobs:
  prereleased:
    strategy:
      matrix:
        component: [first, second]
        runtime: [linux-x64, linux-arm64, mac-x64, mac-arm64, win-x64]
    runs-on: ubuntu-22.04
    steps:
      - run: env | sort
      - run: mkdir dist
      - run: touch dist/${{ matrix.component }}-${{ matrix.runtime }}.zip
      - uses: softprops/action-gh-release@v1
        with:
          files: dist/*
